# Generated by Django 3.0.5 on 2020-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='John Doe', max_length=64),
            preserve_default=False,
        ),
    ]
